add XGetopt.h

diff --git a/cf b/cf
--- a/cf
+++ b/cf
@@ -1,97 +1,52 @@
 #!/bin/bash
+#X="-x"
+#NB=1
+# Use only if default is not correct
+#M32=1
+#M64=1
 
 if test $# != 0 ; then
 cmds=$@
 fi
 
-#X="-x"
-# Use only if default is not correct
-#M32=1
-#M64=1
+CFLAGS=""
+#CFLAGS="-Wall -Wno-unused-variable -Wno-unused-parameter -Wconversion ${CFLAGS}"
+#CFLAGS="-Wall -Wno-unused-variable -Wno-unused-parameter ${CFLAGS}"
+#CFLAGS="-Wconversion"
 
-#NB=1
+stddir="/usr/local"
+PREFIX=/usr/local
 
-#PREFIX="/home/dmh/install/${HOST}"
-if test x$M32 = x1 ; then
-PREFIX="/tmp/install32/${HOST}"
-stddir="/share/ed/local/${HOST}_32"
-elif test x$M64 = x1 ; then
-PREFIX="/tmp/install/${HOST}"
-stddir="/share/ed/local/${HOST}_64"
+if test "x${cmds}" = x ; then
+  cmds=""
 else
-PREFIX="/tmp/install/${HOST}"
-stddir="/share/ed/local/${HOST}"
+for f in $cmds ; do
+  if test "x$f" = "xdistcheck" ; then
+    PREFIX=/tmp/$HOST
+  fi
+done
 fi
-PREFIX=/tmp/install
-if test -f $PREFIX ; then ignore=1; else mkdir -p $PREFIX; fi
-stddir="/usr"
-MAKE=make
-# initial machine dependent parameters
-CFLAGS="-g -O0"
-FFLAGS="-g -O0"
-case "$HOST" in
-  mort)
-    CFLAGS="-std=c99 $CFLAGS"; export CFLAGS
-    ;;
-  sid)
-    ;;
-  flip)
-    CC="c99"; export CC
-    ;;
-  buddy)
-    ;;
-  spock)
-    CFLAGS="-Wall -Wdeclaration-after-statement $CFLAGS"; export CFLAGS
-    ;;
-  Carson)
-    CFLAGS="-Wall -Wdeclaration-after-statement $CFLAGS"; export CFLAGS
-    ;;
-  *)
-    CFLAGS="-Wall $CFLAGS"; export CFLAGS
-    ;;
-esac
 
 if test x$M32 = x1 ; then
 CFLAGS="-m32 $CFLAGS"
 fi
+if test x$M64 = x1 ; then
+CFLAGS="-m64 $CFLAGS"
+fi
 
 # If curl-config is in path, then make no attempt to override
-if curl-config --prefix >/dev/null ; then
-  echo "curl-config found in PATH"
+if curl-config --version >/dev/null ; then
+TMP=`curl-config --cflags`
+CPPFLAGS="$TMP $CPPFLAGS"
+TMP=`curl-config --libs`
+LDFLAGS="$TMP $LDFLAGS"
+TMP=`curl-config --prefix`
+LD_LIBRARY_PATH="$TMP/lib:$LD_LIBRARY_PATH"
 else
-CURLCONFIG="${stddir}/bin/curl-config"
-if test -d "$LOCAL" ; then
-  ignore=0
-else
-  CURLCONFIG="" # Defaults
-  case $HOST in
-  mort)
-    ;;
-  sid)
-    ;;
-  buddy)
-    CURLCONFIG="$stddir/bin/curl-config"
-    PATH="/opt/csw/i386-pc-solaris2.8/bin:$PATH"; export PATH
-    ;;
-  newbuddy)
-    CURLCONFIG="$stddir/bin/curl-config"
-    PATH="/opt/csw/i386-pc-solaris2.8/bin:$PATH"; export PATH
-    ;;
-  *)
-    ;;
-  esac
-fi
+  echo "Cannot find curl-config"
+  exit 1
 fi
 
-if test x$M32 = x1 ; then
-  CFLAGS="-m32 $CFLAGS"; export CFLAGS
-  CXXFLAGS="-m32 $CFLAGS"; export CXXFLAGS
-fi
-
-if test -z "$NB" ; then
-${MAKE} -i maintainer-clean >/dev/null 2>&1
-if autoreconf -i --force ; then ok=1; else exit ; fi
-fi
 
 FLAGS="--prefix ${PREFIX}"
 #FLAGS="${FLAGS} --disable-shared"
@@ -99,13 +54,27 @@ FLAGS="--prefix ${PREFIX}"
 FLAGS="${FLAGS} --enable-remote-tests"
 #FLAGS="${FLAGS} --enable-idl-code"
 #FLAGS="${FLAGS} --disable-disk_storage"
+#FLAGS="${FLAGS} --enable-xgetopt"
 #if test x$CURLCONFIG != x ; then
 #FLAGS="$FLAGS --with-curl-config=$CURLCONFIG"
 #fi
 
 LIBS="$LIBS /share/ed/local/spike/lib/libcurl.a"
 
+export PATH
+export CC
+export CPPFLAGS
+export CFLAGS
+export LDFLAGS
+export LD_LIBRARY_PATH
+
 DISTCHECK_CONFIGURE_FLAGS="$FLAGS"; export DISTCHECK_CONFIGURE_FLAGS
+
+if test -z "$NB" ; then
+${MAKE} -i maintainer-clean >/dev/null 2>&1
+if autoreconf -i --force ; then ok=1; else exit ; fi
+fi
+
 if test -f Makefile ; then ${MAKE} distclean >/dev/null 2>&1 ; fi
 sh $X ./configure ${FLAGS}
 for c in $cmds; do
